### ISSUE TITLE
unhandled exception from mitex.install version 20.12

### ISSUE THREAD

**Issue by filmcriticbeta** [teknowledgist/Chocolatey-packages#45] opened 2021-01-05 10:32 UTC
When attempting to run cinst miktex.install I receive the following error:

====
Unhandled Exception: System.ApplicationException: Cannot combine a path with ':' attempted to combine 'C:\miktex-staging\stable\texmfs\install\miktex\bin\x64\miktexsetup_standalone.exe' with 'C:\ProgramData\chocolatey\lib\miktex.install\tools'
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.combine_paths(String leftItem, String[] rightItems)
   at chocolatey.licensed.infrastructure.app.powershell.GetChocolateyUnzipCmdlet.#=zjaaKepb1B5RF3KWt$A==.#=zgIosR4fy$jJeOrdenw==(Object #=zH6OPSr4=, DataReceivedEventArgs #=z4a5vhrk=)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

===

I *think* the issue is being caused by the tools\miktexsetup-4.0-20.12-x64.zip file being packaged incorrectly.  Windows is unable to decompress the file ( file explorer shows the contents as empty ) whereas 7zip shows a series of nested folders starting with a folder named "c:", which I think is source of the problem.  The previous version of this file ( tools\mitexsetup-4.0-x64.zip ) does not contain any folders, only the miktexsetup.exe file.

**Comment by teknowledgist** [comment] 2021-01-05 14:18
@filmcriticbeta I did notice the zip file with the `c:\` in it, but on my system (and I suppose the Chocolatey.org automatic verification system), when the zip package is expanded, the ":" is converted to "_" and the path just contains a subfolder with the name `C_`.

I don't know why it would unzip differently on your system.  Can you post a full log rather than just the snippet?  if not, can you tell me your version of Windows and Chocolatey.  Hopefully, that will let me zero in on where the problem is.

**Comment by teknowledgist** [comment] 2021-01-05 17:54
Thanks.  Is that the entire log?  I would expect there are a few more lines related to the package cleanup and/or a line or two about the 7zip command exit code.  If you have more to that log, please post it.  If not, I will reach out to the Chocolatey devs to ask about the failure I describe below.  

----

In `Get-ChocolateyUnzip.ps1`, there is a process for logging what is unzipped.  That is the only place I can find where the paths are combined.  In the free version of Chocolatey that I have, they are combined as a string:

    $global:zipFileList.AppendLine($global:zipDestinationFolder + "\" + $line.Substring(2))

which is written to the "C:\ProgramData\chocolatey\lib\miktex.install`zipfilename`.txt" file.  In fact, when I install it on my machine the unzip log file contains:

    C:\ProgramData\chocolatey\lib\miktex.install\tools\C:\miktex-staging\stable\texmfs\install\miktex\bin\x64\miktexsetup_standalone.exe

String concatenation like that should not cause the error you are seeing.  What 7zip does when extracting (in my case) is convert that second ":" to a "_" and the path works.

However, if for some reason, Chocolatey Business that you are using is "combining" them as paths rather than as strings, it would fail since it's not a valid path.  Not having access to Chocolatey Business, I don't know.  

Thanks.

**Comment by filmcriticbeta** [comment] 2021-01-05 18:06
I'm afraid that's were the log file ends. The only thing I haven't included were usernames/etc.

**Comment by teknowledgist** [comment] 2021-01-06 15:54
Just curious:  Does the installer actually get unzipped before the crash?  Because it doesn't appear that there is post-crash cleanup, I don't know if the path would be:

    C:\ProgramData\chocolatey\lib\miktex.install\tools\C_\miktex-staging\stable\texmfs\install\miktex\bin\x64\miktexsetup_standalone.exe

or  

    C:\ProgramData\chocolatey\lib-bad\miktex.install\tools\C_\miktex-staging\stable\texmfs\install\miktex\bin\x64\miktexsetup_standalone.exe

or possibly (but I think unlikely)  

    C:\miktex-staging\stable\texmfs\install\miktex\bin\x64\miktexsetup_standalone.exe

Thanks.

**Comment by filmcriticbeta** [comment] 2021-01-06 16:41
I don't think the unzip is successful.  The closest path I can see is C:\ProgramData\chocolatey\lib-bad\miktex.install\tools .  There is a miktexsetup.exe file located there, but it appears to been extracted from miktexsetup-4.0-x64.zip at some point rather than miktexsetup-4.0-20.12-x64.zip (screen shot attached ).

<img width="1153" alt="Screenshot 2021-01-06 at 16 34 52" src="https://user-images.githubusercontent.com/18420548/103795518-ffd04b00-503d-11eb-85fc-4cbf8cfa4c29.png">

**Comment by teknowledgist** [comment] 2021-01-06 16:59
Can you try running this (cmdline or powershell) to see if 7zip is working:

    "C:\ProgramData\chocolatey\tools\7z.exe" x -aoa -bd -bb1 -o"C:\users\$($env:username)\desktop\7zip Test" -y "C:\ProgramData\chocolatey\lib-bad\miktex.install\tools\miktexsetup-4.0-20.12-x64.zip"

It should build a folder structure on your desktop like "Desktop\7zip Test\C_\miktex-staging\stable\texmfs\install\miktex\bin\x64\miktexsetup_standalone.exe".  If it doesn't, then something is funny about how 7zip works on your machine.  (I don't have access to a 20H2 machine yet, so that could be the difference, not the Chocolatey Business flavor.)

**Comment by filmcriticbeta** [comment] 2021-01-06 17:15
I needed to add the call operator ( & ) at the start of the line, but otherwise it extracted the file as expected:

<img width="794" alt="Screenshot 2021-01-06 at 17 10 07" src="https://user-images.githubusercontent.com/18420548/103799125-930b7f80-5042-11eb-808c-a1a7da7de45d.png">

**Comment by teknowledgist** [comment] 2021-01-06 17:45
Thanks for that.  Do you have any Win10 1909 or other non-20H2 systems with Chocolatey Business that you could test against?

At this point, I don't think there is much more I can do other than wait for MiKTeX to update (with a "properly" zipped installer) or some follow up on [the issue posted for Chocolatey](https://github.com/chocolatey/choco/issues/2168).

**Comment by filmcriticbeta** [comment] 2021-01-08 10:16
Interesting.  I'm getting a different error on one of our student laptops:

2021-01-07 16:48:24,536 10676 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\miktex.install\tools\chocolateyinstall.ps1'
2021-01-07 16:48:24,552 10676 [ERROR] - ERROR: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'FileFullPath64'. Specified method is not supported.
2021-01-07 16:48:24,552 10676 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\miktex.install\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.

[chocolatey.log](https://github.com/teknowledgist/Chocolatey-packages/files/5786548/chocolatey.log)

**Comment by filmcriticbeta** [comment] 2021-01-08 11:56
A bit more digging on the student laptop.  Would the issue be being caused because this is an upgrade install? ( 20.11.0.20201119 is already present):

FileFullPath64 = $ZipFiles | Where-Object {$_ -match 'x64'} is returning an array of two strings "C:\ProgramData\chocolatey\lib-bad\miktex.install\tools\miktexsetup-4.0-x64.zip" and "C:\ProgramData\chocolatey\lib-bad\miktex.install\tools\miktexsetup-4.0-20.12-x64.zip", which would explain the casting error I'm seeing.  I'm guessing the presence of miktexsetup-4.0-x64.zip is a legacy of having the prior version already installed?

**Comment by teknowledgist** [comment] 2021-01-08 13:45
Yes, but...  

In my experience, Chocolatey *sometimes* leaves files that didn't exist in the .nupkg downloaded from the Chocolatey server.  I usually see it with "portable" packages where the application is not installed, but rather, placed within the package folder to be run via shortcut or shim.  When building the package, I have to make sure that Chocolatey cleans out those older stand-alone .exe files before downloading/placing the new version.  I have yet to see Chocolatey leave behind embedded files for older versions.

That said, I'm surprised that older .zip file is still there.  I wouldn't be surprised if the older installer .exe extracted from the zip file were conflicting with the newer installer, and in fact, I modified (locally) the chocolateyinstall.ps1 file to remove any .exe files left behind before the script unpacks the zip file.  I was going to include that change with the next version, but maybe I should push an interim release.

Clearly, you do have two versions of the zip files though, so that is definitely the (or a) problem on this second computer.  However, I really want to blame something other than my package because resolving the problem of old, embedded files being left behind goes way beyond just this package.  

Thanks for testing.  Have you had any success with other systems?

**Comment by filmcriticbeta** [comment] 2021-01-11 14:40
Not yet I'm afraid.  Either of those two errors seems to be affecting most of our clients.

**Comment by filmcriticbeta** [comment] 2021-01-11 15:27
Ok, if I make the following changes it resolves both issues on my systems:

1. In chocolatey.install edit line 7 to read:
$ZipFiles = Get-ChildItem $toolsdir "*$PackageMilestone*.zip" | select-object -ExpandProperty FullName

2. Open both tools\*.zip files in 7zip file manager, and use that to rename the root folder from "c:" to "c".

After rebuilding the nupkg via cpack, I can successfully install it via cinst -s . miktex.install.

Interestingly enough, chocolatey cleaned up the old 20.11 zip files out of \lib after the successful upgrade.

**Comment by teknowledgist** [comment] 2021-01-11 15:34
I've adjusted the ChocolateyInstall.ps1 script and pushed an intermediate update to the package  to resolve the second issue you are seeing.

I don't see a resolution to the first problem (unhandled exception) any time soon unless a new MiKTeX milestone is released with a "properly" zipped download.

**Comment by teknowledgist** [comment] 2021-01-11 15:37
Unfortunately, I can't modify the zip file from what is downloaded.  Users/moderators need to be able to verify that the embedded binaries are the same as the official download.  If I modify it first, the checksum be different.

**Comment by filmcriticbeta** [comment] 2021-01-11 16:29
That's perfectly understandable and the correct position to take.  At the very least I have a viable workaround until the next revision.

**Comment by filmcriticbeta** [comment] 2021-01-20 09:42
Upstream have released a new revision which no longer includes any nested folders.

**Comment by teknowledgist** [comment] 2021-01-20 14:26
Excellent!  I've pushed an updated version of the package.  Assuming it works, I'm going to close this issue as the underlying problem [is posted](https://github.com/chocolatey/choco/issues/2168) and up to the Choco devs to resolve.

Thanks for the heads up.

**Closed by teknowledgist** 2021-01-20 14:26 UTC
